module.exports = {
    GET_UPTIME:"GET_UPTIME",
    SAVE_DRONECONFIG:"SAVE_DRONECONFIG",
    READ_DRONECONFIG:"READ_DRONECONFIG",
    UAVCAST_STATUS:"UAVCAST_STATUS",
    START_UAVCAST:'START_UAVCAST',
    STOP_UAVCAST:'STOP_UAVCAST',
    AUTOSTART_UAVCAST:'AUTOSTART_UAVCAST',
    DISABLE_UAVCAST:'DISABLE_UAVCAST',
    DESTINATION_INFORMATION:'DESTINATION_INFORMATION',
}